### ISSUE TITLE
Use single package manager.

### ISSUE THREAD

**Issue by detronetdip** [Arpan-206/DevArmyKnife#36]
https://github.com/Arpan-206/DevArmyKnife/blob/5b5fdd54809a72a0038be1f857d61f429b10adb3/Dockerfile#L10

We should use any one package manager. As yarn is most preferable here so I think we can convert this line to something equivalent using yarn.

**Comment by Arpan-206** [comment]
Go right ahead!

**Comment by detronetdip** [comment]
https://github.com/Arpan-206/DevArmyKnife/blob/5b5fdd54809a72a0038be1f857d61f429b10adb3/Dockerfile#L5

can you please tell me why you are using `--frozen-lockfile` flag? Is there any specific cause? Because `yarn install` is sufficient to remove packages and installing dependencies as per the [documentation](https://classic.yarnpkg.com/lang/en/docs/cli/prune/).

**Comment by Arpan-206** [comment]
> https://github.com/Arpan-206/DevArmyKnife/blob/5b5fdd54809a72a0038be1f857d61f429b10adb3/Dockerfile#L5
> 
> can you please tell me why you are using `--frozen-lockfile` flag? Is there any specific cause? Because `yarn install` is sufficient to remove extraneous packages and installing dependencies as per the [documentation](https://classic.yarnpkg.com/lang/en/docs/cli/prune/).

Well, it has actually been so long that I don't actually remember, a bad answer I know, but well. So, once you make a PR, Netlify will give you a preview if it's a site change. For docker, I'll have to check it out.

**Comment by detronetdip** [comment]
As I will be modifying the docker file hopefully you have to check it manually but let me cross check everything and I will be opening a pr soon.
